"""Phase 11 document snapshots and constrained personal rules."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0012'; down_revision='0011'; branch_labels=None; depends_on=None
U=postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table('document_lists',sa.Column('id',U,primary_key=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('description',sa.Text),sa.Column('position',sa.String(200)),sa.Column('stage',sa.String(40)),sa.Column('owner_user_id',U,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('document_list_versions',sa.Column('id',U,primary_key=True),sa.Column('list_id',U,sa.ForeignKey('document_lists.id',ondelete='RESTRICT'),nullable=False),sa.Column('version',sa.Integer,nullable=False),sa.Column('state',sa.String(12),nullable=False),sa.Column('created_by_user_id',U,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("state IN ('draft','published','archived')",name='ck_document_version_state'),sa.UniqueConstraint('list_id','version',name='uq_document_list_version'))
    op.create_table('document_list_items',sa.Column('id',U,primary_key=True),sa.Column('version_id',U,sa.ForeignKey('document_list_versions.id',ondelete='RESTRICT'),nullable=False),sa.Column('item_key',sa.String(80),nullable=False),sa.Column('title_ru',sa.String(200),nullable=False),sa.Column('explanation',sa.String(500)),sa.Column('required',sa.Boolean,nullable=False),sa.Column('sort_order',sa.Integer,nullable=False),sa.UniqueConstraint('version_id','item_key',name='uq_document_item_key'))
    op.create_table('candidate_document_sets',sa.Column('id',U,primary_key=True),sa.Column('candidate_id',U,sa.ForeignKey('candidates.id',ondelete='RESTRICT'),nullable=False),sa.Column('list_id',U,sa.ForeignKey('document_lists.id'),nullable=False),sa.Column('version_id',U,sa.ForeignKey('document_list_versions.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','version_id',name='uq_candidate_document_set'))
    op.create_table('candidate_document_statuses',sa.Column('id',U,primary_key=True),sa.Column('set_id',U,sa.ForeignKey('candidate_document_sets.id',ondelete='RESTRICT'),nullable=False),sa.Column('item_key',sa.String(80),nullable=False),sa.Column('status',sa.String(10),nullable=False),sa.Column('changed_by_user_id',U,sa.ForeignKey('users.id'),nullable=False),sa.Column('changed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('row_version',sa.Integer,nullable=False),sa.CheckConstraint("status IN ('missing','received')",name='ck_candidate_document_status'),sa.UniqueConstraint('set_id','item_key',name='uq_candidate_document_status'))
    op.create_table('personal_rules',sa.Column('id',U,primary_key=True),sa.Column('owner_user_id',U,sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('name',sa.String(160),nullable=False),sa.Column('trigger',sa.String(32),nullable=False),sa.Column('action',sa.String(32),nullable=False),sa.Column('parameters',sa.JSON,nullable=False),sa.Column('enabled',sa.Boolean,nullable=False),sa.Column('version',sa.Integer,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("trigger IN ('stage_entered','documents_due')",name='ck_rule_trigger'),sa.CheckConstraint("action IN ('apply_list','document_request','document_reminder')",name='ck_rule_action'))
def downgrade():
    for t in ('personal_rules','candidate_document_statuses','candidate_document_sets','document_list_items','document_list_versions','document_lists'): op.drop_table(t)
